let array = {  
   "features":[  
      {  
         "type":"Feature",
         "properties":{  
            "id":1.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.4,
            "html":2.0,
            "css":2.0,
            "javascript":1.0,
            "bootstrap":2.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":1.0,
            "python":1.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":1.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":2.0,
            "servidores_windows":2.0,
            "aws":1.0,
            "azure":1.0,
            "sql":1.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":54.0,
            "perfil - protagonismo de carreira":22.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":2.0,
            "anos de experiência":2.0,
            "está empregado":"Sim",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.13,
            "html":1.0,
            "css":1.0,
            "javascript":1.0,
            "bootstrap":1.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":0.0,
            "ruby":0.0,
            "java":2.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":1.0,
            "sql":0.0,
            "nosql":0.0,
            "git":0.0,
            "perfil - paixão por tecnologia":52.0,
            "perfil - growth mindset":52.0,
            "perfil - protagonismo de carreira":38.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":3.0,
            "anos de experiência":1.0,
            "está empregado":"Sim",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.45,
            "html":3.0,
            "css":3.0,
            "javascript":3.0,
            "bootstrap":3.0,
            "sass":0.0,
            "less":1.0,
            "angular":1.0,
            "php":2.0,
            "ruby":0.0,
            "java":3.0,
            "python":1.0,
            "csharp":2.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":2.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":2.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":57.0,
            "perfil - growth mindset":54.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":4.0,
            "anos de experiência":3.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.38,
            "html":3.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":1.0,
            "less":1.0,
            "angular":2.0,
            "php":2.0,
            "ruby":0.0,
            "java":2.0,
            "python":0.0,
            "csharp":2.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":1.0,
            "xamarin":1.0,
            "servidores_linux":1.0,
            "servidores_windows":1.0,
            "aws":0.0,
            "azure":0.0,
            "sql":3.0,
            "nosql":1.0,
            "git":3.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":57.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":5.0,
            "anos de experiência":4.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.5,
            "html":4.0,
            "css":4.0,
            "javascript":3.0,
            "bootstrap":3.0,
            "sass":2.0,
            "less":0.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":2.0,
            "python":0.0,
            "csharp":2.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":2.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":2.0,
            "git":3.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":60.0,
            "perfil - protagonismo de carreira":30.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":6.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.65,
            "html":2.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":0.0,
            "less":0.0,
            "angular":2.0,
            "php":0.0,
            "ruby":0.0,
            "java":2.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":2.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":60.0,
            "perfil - growth mindset":58.0,
            "perfil - protagonismo de carreira":37.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":7.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.65,
            "html":3.0,
            "css":2.0,
            "javascript":3.0,
            "bootstrap":2.0,
            "sass":2.0,
            "less":1.0,
            "angular":2.0,
            "php":1.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":2.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":0.0,
            "aws":1.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":56.0,
            "perfil - growth mindset":42.0,
            "perfil - protagonismo de carreira":38.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":8.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.0,
            "html":2.0,
            "css":2.0,
            "javascript":1.0,
            "bootstrap":2.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":51.0,
            "perfil - protagonismo de carreira":22.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":9.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.48,
            "html":3.0,
            "css":3.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":0.0,
            "less":0.0,
            "angular":2.0,
            "php":3.0,
            "ruby":0.0,
            "java":2.0,
            "python":1.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":2.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":2.0,
            "servidores_windows":0.0,
            "aws":1.0,
            "azure":1.0,
            "sql":3.0,
            "nosql":1.0,
            "git":2.0,
            "perfil - paixão por tecnologia":56.0,
            "perfil - growth mindset":58.0,
            "perfil - protagonismo de carreira":21.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":10.0,
            "anos de experiência":2.0,
            "está empregado":"Sim",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.5,
            "html":3.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":2.0,
            "sass":1.0,
            "less":1.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":0.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":3.0,
            "servidores_windows":3.0,
            "aws":1.0,
            "azure":1.0,
            "sql":2.0,
            "nosql":1.0,
            "git":1.0,
            "perfil - paixão por tecnologia":64.0,
            "perfil - growth mindset":35.0,
            "perfil - protagonismo de carreira":22.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":11.0,
            "anos de experiência":2.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.25,
            "html":1.0,
            "css":1.0,
            "javascript":1.0,
            "bootstrap":1.0,
            "sass":1.0,
            "less":0.0,
            "angular":1.0,
            "php":0.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":0.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":40.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":27.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":12.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":1.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.13,
            "html":3.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":2.0,
            "less":0.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":2.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":61.0,
            "perfil - growth mindset":54.0,
            "perfil - protagonismo de carreira":19.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":13.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.23,
            "html":2.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":2.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":1.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":64.0,
            "perfil - growth mindset":31.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":14.0,
            "anos de experiência":1.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.55,
            "html":2.0,
            "css":3.0,
            "javascript":2.0,
            "bootstrap":2.0,
            "sass":1.0,
            "less":2.0,
            "angular":1.0,
            "php":0.0,
            "ruby":0.0,
            "java":0.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":2.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":1.0,
            "aws":1.0,
            "azure":1.0,
            "sql":1.0,
            "nosql":1.0,
            "git":1.0,
            "perfil - paixão por tecnologia":60.0,
            "perfil - growth mindset":40.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":22.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":15.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.55,
            "html":3.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":1.0,
            "less":1.0,
            "angular":2.0,
            "php":3.0,
            "ruby":2.0,
            "java":1.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":2.0,
            "servidores_linux":2.0,
            "servidores_windows":1.0,
            "aws":1.0,
            "azure":1.0,
            "sql":2.0,
            "nosql":1.0,
            "git":3.0,
            "perfil - paixão por tecnologia":63.0,
            "perfil - growth mindset":45.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":16.0,
            "anos de experiência":5.0,
            "está empregado":"Sim",
            "número de graduações completas":2.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":1.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.58,
            "html":2.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":2.0,
            "sass":1.0,
            "less":0.0,
            "angular":2.0,
            "php":2.0,
            "ruby":2.0,
            "java":1.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":2.0,
            "aws":0.0,
            "azure":0.0,
            "sql":3.0,
            "nosql":2.0,
            "git":1.0,
            "perfil - paixão por tecnologia":48.0,
            "perfil - growth mindset":35.0,
            "perfil - protagonismo de carreira":21.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":17.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.4,
            "html":3.0,
            "css":3.0,
            "javascript":1.0,
            "bootstrap":2.0,
            "sass":2.0,
            "less":0.0,
            "angular":1.0,
            "php":2.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":0.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":40.0,
            "perfil - protagonismo de carreira":23.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":18.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.3,
            "html":2.0,
            "css":2.0,
            "javascript":1.0,
            "bootstrap":1.0,
            "sass":1.0,
            "less":1.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":2.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":48.0,
            "perfil - growth mindset":60.0,
            "perfil - protagonismo de carreira":40.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":19.0,
            "anos de experiência":8.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.45,
            "html":3.0,
            "css":2.0,
            "javascript":1.0,
            "bootstrap":3.0,
            "sass":0.0,
            "less":0.0,
            "angular":0.0,
            "php":2.0,
            "ruby":1.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":2.0,
            "servidores_windows":2.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":60.0,
            "perfil - protagonismo de carreira":30.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":20.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.5,
            "html":3.0,
            "css":2.0,
            "javascript":3.0,
            "bootstrap":1.0,
            "sass":1.0,
            "less":0.0,
            "angular":2.0,
            "php":2.0,
            "ruby":0.0,
            "java":1.0,
            "python":2.0,
            "csharp":2.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":58.0,
            "perfil - growth mindset":51.0,
            "perfil - protagonismo de carreira":16.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":21.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.68,
            "html":3.0,
            "css":2.0,
            "javascript":3.0,
            "bootstrap":2.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":3.0,
            "ruby":0.0,
            "java":1.0,
            "python":1.0,
            "csharp":2.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":3.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":46.0,
            "perfil - growth mindset":52.0,
            "perfil - protagonismo de carreira":22.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":22.0,
            "anos de experiência":2.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.2,
            "html":2.0,
            "css":2.0,
            "javascript":1.0,
            "bootstrap":2.0,
            "sass":1.0,
            "less":1.0,
            "angular":0.0,
            "php":2.0,
            "ruby":0.0,
            "java":0.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":0.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":57.0,
            "perfil - growth mindset":60.0,
            "perfil - protagonismo de carreira":26.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":23.0,
            "anos de experiência":7.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.3,
            "html":3.0,
            "css":3.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":1.0,
            "less":0.0,
            "angular":1.0,
            "php":2.0,
            "ruby":3.0,
            "java":3.0,
            "python":2.0,
            "csharp":1.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":1.0,
            "aws":0.0,
            "azure":1.0,
            "sql":2.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":51.0,
            "perfil - protagonismo de carreira":30.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":24.0,
            "anos de experiência":3.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":2.0,
            "nota prova técnica":0.05,
            "html":3.0,
            "css":3.0,
            "javascript":3.0,
            "bootstrap":3.0,
            "sass":1.0,
            "less":1.0,
            "angular":2.0,
            "php":2.0,
            "ruby":0.0,
            "java":0.0,
            "python":1.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":0.0,
            "aws":2.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":2.0,
            "git":1.0,
            "perfil - paixão por tecnologia":64.0,
            "perfil - growth mindset":54.0,
            "perfil - protagonismo de carreira":25.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":25.0,
            "anos de experiência":4.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.23,
            "html":2.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":1.0,
            "sass":0.0,
            "less":0.0,
            "angular":0.0,
            "php":1.0,
            "ruby":0.0,
            "java":0.0,
            "python":1.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":0.0,
            "aws":1.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":55.0,
            "perfil - protagonismo de carreira":23.0,
            "perfil - respeito":22.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":26.0,
            "anos de experiência":0.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.35,
            "html":2.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":1.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":0.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":48.0,
            "perfil - growth mindset":31.0,
            "perfil - protagonismo de carreira":22.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":27.0,
            "anos de experiência":0.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.75,
            "html":4.0,
            "css":3.0,
            "javascript":4.0,
            "bootstrap":2.0,
            "sass":2.0,
            "less":2.0,
            "angular":3.0,
            "php":2.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":2.0,
            "nodejs":4.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":3.0,
            "xamarin":0.0,
            "servidores_linux":3.0,
            "servidores_windows":3.0,
            "aws":2.0,
            "azure":0.0,
            "sql":3.0,
            "nosql":3.0,
            "git":3.0,
            "perfil - paixão por tecnologia":53.0,
            "perfil - growth mindset":40.0,
            "perfil - protagonismo de carreira":22.0,
            "perfil - respeito":24.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":28.0,
            "anos de experiência":5.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.1,
            "html":3.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":3.0,
            "less":0.0,
            "angular":1.0,
            "php":2.0,
            "ruby":0.0,
            "java":0.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":1.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":60.0,
            "perfil - growth mindset":43.0,
            "perfil - protagonismo de carreira":24.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":29.0,
            "anos de experiência":1.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.03,
            "html":2.0,
            "css":2.0,
            "javascript":1.0,
            "bootstrap":3.0,
            "sass":1.0,
            "less":0.0,
            "angular":1.0,
            "php":2.0,
            "ruby":0.0,
            "java":1.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":1.0,
            "perfil - paixão por tecnologia":56.0,
            "perfil - growth mindset":44.0,
            "perfil - protagonismo de carreira":29.0,
            "perfil - respeito":15.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":30.0,
            "anos de experiência":2.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.48,
            "html":3.0,
            "css":3.0,
            "javascript":3.0,
            "bootstrap":2.0,
            "sass":2.0,
            "less":1.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":2.0,
            "python":0.0,
            "csharp":0.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":1.0,
            "git":3.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":52.0,
            "perfil - protagonismo de carreira":29.0,
            "perfil - respeito":13.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":31.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.83,
            "html":3.0,
            "css":3.0,
            "javascript":2.0,
            "bootstrap":3.0,
            "sass":1.0,
            "less":1.0,
            "angular":1.0,
            "php":3.0,
            "ruby":0.0,
            "java":0.0,
            "python":2.0,
            "csharp":0.0,
            "nodejs":0.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":1.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":1.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":1.0,
            "git":0.0,
            "perfil - paixão por tecnologia":55.0,
            "perfil - growth mindset":43.0,
            "perfil - protagonismo de carreira":26.0,
            "perfil - respeito":27.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":32.0,
            "anos de experiência":1.0,
            "está empregado":"Não",
            "número de graduações completas":0.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.4,
            "html":2.0,
            "css":2.0,
            "javascript":2.0,
            "bootstrap":1.0,
            "sass":0.0,
            "less":0.0,
            "angular":1.0,
            "php":1.0,
            "ruby":0.0,
            "java":2.0,
            "python":0.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":0.0,
            "servidores_windows":0.0,
            "aws":0.0,
            "azure":0.0,
            "sql":1.0,
            "nosql":0.0,
            "git":2.0,
            "perfil - paixão por tecnologia":59.0,
            "perfil - growth mindset":46.0,
            "perfil - protagonismo de carreira":32.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":33.0,
            "anos de experiência":1.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.43,
            "html":3.0,
            "css":3.0,
            "javascript":2.0,
            "bootstrap":1.0,
            "sass":1.0,
            "less":1.0,
            "angular":1.0,
            "php":2.0,
            "ruby":2.0,
            "java":2.0,
            "python":1.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":1.0,
            "ionic":0.0,
            "xamarin":0.0,
            "servidores_linux":2.0,
            "servidores_windows":3.0,
            "aws":1.0,
            "azure":0.0,
            "sql":2.0,
            "nosql":1.0,
            "git":2.0,
            "perfil - paixão por tecnologia":64.0,
            "perfil - growth mindset":43.0,
            "perfil - protagonismo de carreira":24.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      },
      {  
         "type":"Feature",
         "properties":{  
            "id":34.0,
            "anos de experiência":2.0,
            "está empregado":"Sim",
            "número de graduações completas":1.0,
            "número de graduações incompletas":0.0,
            "número de pós-graduações completas":0.0,
            "número de pós-graduações incompletas":0.0,
            "nota prova técnica":0.32,
            "html":3.0,
            "css":3.0,
            "javascript":3.0,
            "bootstrap":3.0,
            "sass":3.0,
            "less":3.0,
            "angular":3.0,
            "php":3.0,
            "ruby":2.0,
            "java":1.0,
            "python":1.0,
            "csharp":1.0,
            "nodejs":1.0,
            "objectivec":0.0,
            "swift":0.0,
            "android":0.0,
            "ionic":2.0,
            "xamarin":0.0,
            "servidores_linux":2.0,
            "servidores_windows":3.0,
            "aws":3.0,
            "azure":3.0,
            "sql":3.0,
            "nosql":3.0,
            "git":3.0,
            "perfil - paixão por tecnologia":64.0,
            "perfil - growth mindset":37.0,
            "perfil - protagonismo de carreira":23.0,
            "perfil - respeito":25.0
         },
         "geometry":null
      }
   ]
}